### PR TITLE
Trailheads transform WIP

### LINKED ISSUE #37: trailhead "id" value identification/creation
### Goal

Identify whether or not the trailhead file contains unique "id" values. If it does, assign those values to the "id" property required by OpenTrails. If not, create unique ids for each trailhead. 

key strings: "id" "OBJECTID"
#### Approach for Creating unique IDs

We have been creating unique IDs for stewards and trail segments using a scheme recommended by [OpenTrails](https://docs.google.com/a/codeforamerica.org/document/d/1KF8KAio-SqGHhh9oFY_KjfwIi3PePOHg7KfTSPh27fc/edit#bookmark=id.ukk6kpfl3ej8)

We build a unique ID string using the steward id (derived from the steward URL), the type of feature (in this case trailheads), and either the name-string or a GUID provided by a service like Brooklyn Integers.

We have not yet encountered a trailhead dataset that has unique IDs for each feature. For the Ohio data, trailheads are simply enumerated using an OBJECTID.

### LINKED ISSUE #41: trailhead "address" identification/creation
### Goals

Trailheads are points of access for trails. Thus, they are often used as destinations for routing end users from their current location to the trail.

Thus, we want to identify whether the trailhead data file uploaded contains a string representing a street address.

_note that the "address" field is not required_
#### Approach

key strings: "add" "address" "street "siteaddr"
- Check column names for key strings 
  - If an column containing street address values exist, use those values for the "address" field
  - If not address exists, leave the "address" field null.

### LINKED ISSUE #42: trailhead "parking" identification/creation
### Goal

Identify whether or not the uploaded trailhead data contains an indication as to whether parking is available on site. 
#### Approach

key strings: "park" "parking", "non parking" "none" "no parking" "parking lot" "roadside"

In the majority of sample data, no column describing the presence of parking exists. In this case, leave the value of the parking attribute null.

In a minority of sample data we have on hand, a column specifying whether or not parking is appropriate does exist.  

However, there is heterogeneity the values provided. Some data uses a boolean value, other uses strings such as "Non Parking" "Parking Lot" "Roadside Parking" "None" or "No Parking". Thus the value of the "parking" field should be based on the presence of these values.

### LINKED ISSUE #43: trailhead "drinkwater" identification/creation
### Goal

Identify whether or not the uploaded trailhead data contains an indication as to whether drinking water is available on site. 
#### Approach

key strings: "water" "drinkingwa", "drinkwater"

In the majority of sample data, no column describing the presence of drinking water exists. In this case, leave the value of the "drinkwater" attribute null.

In a minority of sample data we have on hand, a column specifying whether or not water is available does exist, and the values provided are booleans.
- Determine whether a column name containing one or more key strings exists
- If so, translate the boolean values provided into the OpenTrails-compliant boolean "yes" or "no"
- If not, create the property "drinkwater" but leave the value null.

### LINKED ISSUE #45: trailhead "kiosk" identification/creation
### Goal

Identify whether or not the uploaded trailhead data contains an indication as to whether or not an information kiosk or installation is available on site. 
#### Approach

key strings: "info" "kiosk", "information"

In the majority of sample data, no column describing the presence of information assets exists. In this case, leave the value of the "kiosk" attribute null.

In a minority of sample data we have on hand, a column specifying whether or not an information kiosk is available does exist, and the values provided are booleans.
- determine whether a column name containing one or more key strings exists
- if so, translate the boolean values provided into the OpenTrails-compliant boolean "yes" or "no"
- If not, create the property "kiosk" but leave the value null.

### LINKED ISSUE #73: Author error pages for trailhead data
Create error pages for all required and recommended fields
- [x] trail_ids
- [ ] steward_id
- [x] id
- [x] restrooms
- [x] kiosk
- [x] drinkwater
- [x] parking
- [x] address

### PR DESCRIPTION
**Pull request by alanjosephwilliams**
- This PR should:
  - Close #73. Each error now has a template. The only exception from the list in that issue is "steward_id". There should never be that error, since we create that file/value in the transformation process.
  - Close #43 by transforming fields indicating the presence of drinking water.
  - Close #45 by transforming fields indicating the presence of information kiosks.
  - Close #37 by transforming fields containing a unique ID for each trailhead feature.
  - Close #41 by transforming fields containing strings representing an address.
  - Close #42 by transforming fields indicating the presence of parking (including fields that indicate the presence of parking based on a few different strings, documented in the issue)

(Perhaps it is unconventional to indicate what a PR does _not_ do, but it seems prudent to mention that...)
- This PR does not address:
  - # 38 steward_id: Per the pattern of trail_segments, this code currently just assigns "0" as the steward_id for the trailhead. The steward_id created when stewards.csv is populated by the user via a form should replace this value at some point in the transformation process.
  - # 39 trail_ids: it is not immediately clear to me how to grab the strings found in fields such as "trail name", then cross-reference those strings with the "name" field of named_trails.csv, grab the associated "id" for that row, and push each of those values into an array here.
  - #40 area_ids: we do not currently handle area files, and thus there are no area_ids to assign.
- Apologies for the duplicate commit message.

### CODE REVIEW

**Comment by alanjosephwilliams** [comment]
Bah, just saw the Travis error. Investigating.

**Comment by alanjosephwilliams** [comment]
This is the error, not quite sure yet how to rectify:

_The command "sudo apt-get install gdal-bin" failed and exited with 100 during ._

**Comment by migurski** [comment]
Sounds like there are a few solutions out there: http://gis.stackexchange.com/questions/82270/unable-to-upgrade-gdal-bin-from-1-9-to-1-10-on-ubuntu-12-04, maybe try asking by version? This smells like a weird bug in Ubuntu's package manager system.

**Comment by migurski** [comment]
I think the Travis errors are their fault. The tests are running fine locally and I've confirmed that `gdal-bin` exists and works on another copy of Ubuntu Precise, so I'm going to ignore the failure for now.

**Pull request merged**
