### PR TITLE
Adding Esri 'Stuff'

### PR DESCRIPTION
**Pull request by jonahadkins**
Not sure if it's needed, but i would find this useful, aka make it easier to get my data into the OT Spec.

Contains a skeleton file geodatabase with processing tools in a ArcToolbox, skeleton shapefiles, and an XML schema doc for importing schema into a existing gdb

Need to test the toolbox tools, to make sure a straight copy works...also included a tool from the [Esri2Open](https://github.com/project-open-data/esri2open) toolbox for converting Esri formats to geojson

Also, if you like i can write-up a markdown doc detailing folder contents

### CODE REVIEW

**Comment by lyzidiamond** [comment]
Later today (if it's cool with everyone) I'll pull this down on the Windows machine at CfA and test it out with ArcGIS. If it's working there, I'll give it a merge go-ahead. @ryanbranciforte I know you have ArcGIS on your laptop, so if you'd rather do it let me know. Otherwise, that's my plan! :bird: :girl: :monkey:

**Comment by lyzidiamond** [comment]
This looks awesome! @alanjosephwilliams and I think this should have its own repo. We're thinking about maybe stringing that toolbox together as one python script, so the repo will be a place for that! Alan is currently adding you to the OpenTrails org, so you'll be able to create that repo. :smile: Let us know if you have questions!

**Comment by ryanbranciforte** [comment]
great work folks! really excited to see this come together. we've heard from many park agencies that they would like an in-esri solution for transforming to OT.

**Comment by jonahadkins** [comment]
Added a [new repo](https://github.com/opentraildata/esri-to-opentrails), copied up features, and added Generalize and Append tools to toolset. 

:earth_americas: :man: :earth_americas:

**Pull request closed without merging**
