### PR TITLE
Add Instructions for Testing and Running

### PR DESCRIPTION
**Pull request by ungoldman**
Noticed there were no explicit instructions for testing and running. Not sure if this is the pythonest way to do it:

---
## Test

```
python tests.py
```
## Run

```
gunicorn open_trails:app
```

---

Also got rid of weird em-dash characters and fixed the gitignore.

### CODE REVIEW

**Comment by lyzidiamond** [comment]
This may be a good place to drop in stuff from howto: https://github.com/codeforamerica/howto/blob/master/Python-Virtualenv.md

**Comment by migurski** [comment]
I think `honcho start` (or `foreman start`) would be more appropriate for the latter, plus a link to [Procfile howto](https://github.com/codeforamerica/howto/blob/master/Procfile.md).

**Comment by lyzidiamond** [comment]
Ah yes @migurski that's a better one :smiley_cat:

**Comment by ungoldman** [comment]
Ok, updated and rebased.

**Comment by migurski** [comment]
Yay!

**Pull request merged**
